# Use postgres/example as user/password credentials
version: '3'

services:
  db:
    image: postgres:14.3
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
    container_name: local-postgresql
    volumes:
      - ./postgres_14_3-data:/var/lib/postgresql/data
